### ISSUE TITLE
Optimize hardware setup

### ISSUE THREAD

**Issue by RolandColored** [RolandColored/smartmeter#4]
- [x] Better fixation of gas sensor
- [ ] ~Lay ethernet cable to raspberry pi~ Not needed anymore because of new access point in kitchen is within range.

**Comment by mrebbert** [comment]
Hi Roland!

first of all, thanks for your work. I try to build up sth similar and got also an Pipersberg G4 RF1 c (mm) and got some trouble to find the right spot to fixate the sensor.
I use this holder: https://www.thingiverse.com/thing:4050360 and move the drilling around, actually with no success.

Could you give me a hint here?

Best Regards,
Markus

PS: I saw you're searching for a solution to read the energy meter. May be this could help you out: https://github.com/mrebbert/FerrarisPowerMeter

**Comment by RolandColored** [comment]
Hi mrebbert,

did you already tried it without the holder to check if it works at all? For me, the sensor it is also very sensitive to find the sweet spot. It's more on the bottom right side of that "circle" where the original sensor would go. The head of the sensor also needs to lay 100% flat on the meter's case. If there is already 1mm of space between, it won't work anymore.

And thank you for the hints!

Kind regards
Roland

**Comment by mrebbert** [comment]
Hi Roland,

Update: found it in max right-top position. Completely different from other descriptions.
Thanks again! ~Markus

to be honest, I haven't tried it by hand yet because the circulation times, even with the service position on the heater, have been too long for me so far. But I probably won't be able to avoid it. 

Thank you for the advice on positioning. I'll try that. There seem to be differences depending on the year of manufacture.

Best Regards,
Markus

**Comment by RolandColored** [comment]
I would like to give an update here. I let someone print out the holder you noted which technically fits very well, but the position did also not work for me. After fiddling around a lot I finally gave up on the sensor because it's range is too bad.

I ordered a new sensor: https://www.amazon.de/gp/product/B07XHRG8S9/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1
It comes with a higher detection area (8mm instead of 4mm) and also operates at 5V which is perfect for the RaspberryPi. It's quite thicker than the other sensor so I needed to drill a bigger hole into the holder, but now it's working perfectly.

**Comment by riegelbrau** [comment]
Hello,
I'm working on a solution for the Pipersberg G4 RF1 c as well. I have the 4 mm sensor and the LED is blinking, when positioned correctly. What I need is the 3D printable holder mentioned above by @mrebbert, but the STL file is no longer available. The link leads to error 404. At another location the file is also no longer downloadable: https://3dmixers.com/m/289612-halterung-pipersberg-g4-rf1-c . 

Does anyone have the downloaded file and would it provide please?

Thanks a lot!

Christoph

**Comment by RolandColored** [comment]
I still have the files around me.

[Halterung Pipersberg G4 Rf1 C.zip](https://github.com/RolandColored/smartmeter/files/9485372/Halterung.Pipersberg.G4.Rf1.C.zip)

**Comment by riegelbrau** [comment]
Thank you!

Gruß Christoph
Am 4. September 2022 21:24:35 schrieb Roland Kahlert 
***@***.***>:

**Comment by JackTora** [comment]
Hello Roland,

Great work, many thanks for it. I would like to copy your project and need the STL files as well. Where can I get them? Have you also adapted the 3D print files to the 8mm variant?
Thanks a lot!

Stefan

**Comment by RolandColored** [comment]
Unfortunately I was not able to adapt the model for the bigger diameter. Would to love see if someone managed it. 😃 

**Update** A new version of the holder is available here: https://www.printables.com/de/model/252308-halterung-pipersberg-g4-rf1-c
